name: Container CI/CD Workflow

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  test:
    uses: lcacollect/.github/.github/workflows/test-python.yaml@main
  publish-schema:
    if: github.event_name != 'pull_request'
    uses: lcacollect/.github/.github/workflows/publish-graphql.yaml@main
    needs: test
  build-container:
    uses: lcacollect/.github/.github/workflows/build-image.yaml@main
    needs: test
    with:
      tag: ${{ github.run_number }}
      registry: ""
      name: ""
#  publishchart:
#    if: github.event_name != 'pull_request'
#    uses: lcacollect/.github/.github/workflows/publish-chart.yaml@main