on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      branch:
        required: true
        type: string
      storage-account:
        required: true
        type: string
      container-name:
        required: true
        type: string
    secrets:
      azure-credentials:
        required: true

jobs:
  publish-schema:
    name: Publish GraphQL Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload to Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch --sas-token ${{ secrets.azure-credentials }} --account-name ${{ inputs.storage-account }} --source ${{ inputs.container-name }} --pattern "${{ inputs.name }}/${{ inputs.branch }}/*"
            az storage blob upload-batch --sas-token ${{ secrets.azure-credentials }} --account-name ${{ inputs.storage-account }} --auth-mode key -d ${{ inputs.container-name }} --destination-path "${{ inputs.name }}/${{ inputs.branch }}" -s graphql/