on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      receiver_repo:
        required: true
        type: string
    secrets:
      dispatch_token:
        required: true

jobs:
  send-dispatch:
    name: Send Repository Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.dispatch_token }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ inputs.receiver_repo }}/dispatches \
            -d '{"event_type":"workflow_completed","client_payload":{"branch":"${{ github.ref_name }}", "repo":"${{ inputs.repo_name }}"}}'