on:
  workflow_call:
    inputs:
      run_e2e:
        required: false
        type: boolean
        default: false
      node_version:
        required: false
        type: string
        default: "18.x"
      router_url:
        required: true
        type: string
      artifact_name:
        required: false
        type: string
        default: "lcacollect-app"
      aad_client_id:
        required: true
        type: string
      aad_tenant_id:
        required: true
        type: string
      aad_app_client_id:
        required: true
        type: string
    secrets:
      VITE_MUI_LICENSE:
        required: true
      CYPRESS_AAD_APP_CLIENT_SECRET:
        required: false
      CYPRESS_TEST_USER_EMAIL:
        required: false
      CYPRESS_TEST_USER_PASSWORD:
        required: false

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: "npm"
      - name: Install
        run: npm ci
    
      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

      - name: Unit Tests
        run: npm run test

      - name: E2E Tests
        run: npm run e2e
        if: ${{ inputs.run_e2e }}
        env:
          TERM: xterm
          VITE_APOLLO_ROUTER_URL: "http://localhost:4000/graphql"
          VITE_AAD_CLIENT_ID: ${{ inputs.aad_client_id }}
          VITE_AAD_TENANT_ID: ${{ inputs.aad_tenant_id }}
          VITE_AAD_APP_CLIENT_ID: ${{ inputs.aad_app_client_id }}
          VITE_MUI_LICENSE: ${{ secrets.VITE_MUI_LICENSE }}
          CYPRESS_AAD_TENANT_ID: ${{ inputs.aad_tenant_id }}
          CYPRESS_AAD_CLIENT_ID: ${{ inputs.aad_app_client_id }}
          CYPRESS_AAD_APP_CLIENT_SECRET: ${{ secrets.CYPRESS_AAD_APP_CLIENT_SECRET }}
          CYPRESS_TEST_USER_EMAIL: ${{ secrets.CYPRESS_TEST_USER_EMAIL }}
          CYPRESS_TEST_USER_PASSWORD: ${{ secrets.CYPRESS_TEST_USER_PASSWORD }}
      
      - name: Build
        run: npm run build
        env:
          VITE_APOLLO_ROUTER_URL: ${{ inputs.router_url }}
          VITE_AAD_CLIENT_ID: ${{ inputs.aad_client_id }}
          VITE_AAD_TENANT_ID: ${{ inputs.aad_tenant_id }}
          VITE_AAD_APP_CLIENT_ID: ${{ inputs.aad_app_client_id }}
          VITE_MUI_LICENSE: ${{ secrets.VITE_MUI_LICENSE }}
          VITE_PROJECT_STAGE_LIST: "A1-A3,C3,C4,D"

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v3
        if: github.event_name != 'pull_request'
        with:
          name: ${{ inputs.artifact_name }}
          path: ./dist