on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"

jobs:
  test:
    name: Test Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv sync --dev
      
      - name: Check Formatting
        run: pipenv run black --check

      - name: Check ISort
        run: pipenv run isort --check

      - name: Run PyTest
        run:  pipenv run pytest
